import { supabase, isConfigured, categories } from './config.js'
const $=s=>document.querySelector(s); const msg=$('#adminMessage');
function showMessage(text,error=false){msg.textContent=text;msg.className=`form-message${error?' error':''}`;setTimeout(()=>msg.textContent='',4500)}
async function requireAdmin(){if(!isConfigured){$('#loginMessage').textContent='اربط المشروع بـ Supabase أولًا كما هو موضح في README.';return}const {data:{session}}=await supabase.auth.getSession();if(session)showDashboard();supabase.auth.onAuthStateChange((_event,s)=>s?showDashboard():showLogin())}
function showLogin(){$('#loginView').classList.remove('admin-hidden');$('#dashboard').classList.add('admin-hidden');$('#logoutBtn').classList.add('admin-hidden')}
function showDashboard(){$('#loginView').classList.add('admin-hidden');$('#dashboard').classList.remove('admin-hidden');$('#logoutBtn').classList.remove('admin-hidden');loadAll()}
async function loadAll(){const [{data:offers,error},{data:news}]=await Promise.all([supabase.from('offers').select('*').order('created_at',{ascending:false}),supabase.from('news').select('*').order('sort_order')]);if(error){showMessage('لا تملك صلاحية الإدارة أو تعذّر تحميل البيانات.',true);return}$('#pendingCount').textContent=offers.filter(x=>x.status==='pending').length;$('#publishedCount').textContent=offers.filter(x=>x.status==='published').length;$('#newsCount').textContent=news?.length||0;$('#offersTable').innerHTML=offers.map(o=>`<tr><td><b>${o.operation} ${o.category}</b><br>${o.amount}</td><td>${o.city}</td><td>${o.status}</td><td class="actions">${o.status==='pending'?`<button class="mini approve" data-action="published" data-id="${o.id}">موافقة</button><button class="mini reject" data-action="rejected" data-id="${o.id}">رفض</button>`:''}<button class="mini" data-offer-edit="${o.id}">تعديل</button><button class="mini" data-action="hidden" data-id="${o.id}">إخفاء</button><button class="mini reject" data-action="delete" data-id="${o.id}">حذف</button></td></tr>`).join('');$('#newsTable').innerHTML=(news||[]).map(n=>`<tr><td>${n.content}</td><td>${n.sort_order}</td><td class="actions"><button class="mini" data-news-edit="${n.id}">تعديل</button><button class="mini" data-news-toggle="${n.id}" data-active="${!n.active}">${n.active?'إخفاء':'إظهار'}</button><button class="mini reject" data-news-delete="${n.id}">حذف</button></td></tr>`).join('');bindActions()}
function bindActions(){document.querySelectorAll('[data-offer-edit]').forEach(b=>b.onclick=async()=>{const amount=prompt('المبلغ أو الكمية الجديدة:');if(!amount)return;const price=prompt('السعر الجديد (يمكن تركه فارغًا):')||'';const city=prompt('المدينة الجديدة:');if(!city)return;const {error}=await supabase.from('offers').update({amount,price,city}).eq('id',b.dataset.offerEdit);if(error)showMessage(error.message,true);else loadAll()});document.querySelectorAll('[data-news-edit]').forEach(b=>b.onclick=async()=>{const content=prompt('نص الخبر الجديد:');if(!content)return;const {error}=await supabase.from('news').update({content}).eq('id',b.dataset.newsEdit);if(error)showMessage(error.message,true);else loadAll()});document.querySelectorAll('[data-action]').forEach(b=>b.onclick=async()=>{if(b.dataset.action==='delete'){if(!confirm('حذف العرض نهائيًا؟'))return;await supabase.from('offers').delete().eq('id',b.dataset.id)}else await supabase.from('offers').update({status:b.dataset.action}).eq('id',b.dataset.id);loadAll()});document.querySelectorAll('[data-news-delete]').forEach(b=>b.onclick=async()=>{if(confirm('حذف الخبر؟')){await supabase.from('news').delete().eq('id',b.dataset.newsDelete);loadAll()}});document.querySelectorAll('[data-news-toggle]').forEach(b=>b.onclick=async()=>{await supabase.from('news').update({active:b.dataset.active==='true'}).eq('id',b.dataset.newsToggle);loadAll()})}
$('#loginForm').onsubmit=async e=>{e.preventDefault();const b=e.currentTarget.querySelector('button');b.disabled=true;const {email,password}=Object.fromEntries(new FormData(e.currentTarget));const {error}=await supabase.auth.signInWithPassword({email,password});$('#loginMessage').textContent=error?'بيانات الدخول غير صحيحة.':'';b.disabled=false};$('#logoutBtn').onclick=()=>supabase.auth.signOut();
$('#newsForm').onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));values.sort_order=Number(values.sort_order);const {error}=await supabase.from('news').insert(values);if(error)showMessage(error.message,true);else{e.currentTarget.reset();showMessage('تم نشر الخبر.');loadAll()}};
$('#adminOfferForm').onsubmit=async e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.currentTarget));values.status='published';const {error}=await supabase.from('offers').insert(values);if(error)showMessage(error.message,true);else{e.currentTarget.reset();showMessage('تم نشر العرض.');loadAll()}};
$('#adminOfferForm [name=category]').innerHTML=categories.slice(1).map(c=>`<option>${c}</option>`).join('');requireAdmin()
