import { supabase, isConfigured, categories } from './config.js'

const demoOffers = [
  {id:'demo-1',operation:'بيع',category:'الدولار',amount:'1,000 دولار',price:'سعر تجريبي: 6.50 د.ل',city:'طرابلس',created_at:'2026-09-19T09:30:00Z',status:'منشور',whatsapp:'218910000000',description:'بيانات توضيحية فقط وليست عرضًا حقيقيًا.'},
  {id:'demo-2',operation:'شراء',category:'اليورو',amount:'500 يورو',price:'سعر تجريبي: 7.10 د.ل',city:'بنغازي',created_at:'2026-09-18T16:20:00Z',status:'منشور',whatsapp:'218920000000',description:'بيانات توضيحية فقط وليست عرضًا حقيقيًا.'},
  {id:'demo-3',operation:'بيع',category:'الحوالات',amount:'حوالة بقيمة 2,000 د.ل',price:'السعر حسب الاتفاق',city:'مصراتة',created_at:'2026-09-18T12:00:00Z',status:'منشور',whatsapp:'218930000000',description:'بيانات توضيحية فقط وليست عرضًا حقيقيًا.'}
]
let offers=[], activeCategory='الكل', deferredPrompt, demoMode=false
const $ = s => document.querySelector(s)

function safe(value=''){ const el=document.createElement('span'); el.textContent=value; return el.innerHTML }
function renderCategories(){ $('#categories').innerHTML=categories.map(c=>`<button class="chip ${c===activeCategory?'active':''}" data-category="${c}">${c}</button>`).join(''); document.querySelectorAll('.chip').forEach(b=>b.onclick=()=>{activeCategory=b.dataset.category;renderCategories();renderOffers()}); const select=$('[name=category]'); select.innerHTML=categories.slice(1).map(c=>`<option>${c}</option>`).join('') }
function renderOffers(){ const q=$('#searchInput').value.trim().toLowerCase(); const shown=offers.filter(o=>(activeCategory==='الكل'||o.category===activeCategory)&&[o.category,o.city,o.operation,o.description].some(v=>(v||'').toLowerCase().includes(q))); $('#resultsCount').textContent=`${shown.length} عرض`; $('#statusMessage').textContent=demoMode?'وضع المعاينة: البيانات التالية تجريبية وليست أسعار سوق حقيقية.':(shown.length?'':'لا توجد عروض مطابقة حاليًا.'); $('#offersGrid').innerHTML=shown.map(o=>{const phone=(o.whatsapp||'').replace(/\D/g,'');const msg=encodeURIComponent(`مرحبًا، أتواصل بشأن عرض ${o.operation} ${o.amount} المنشور في سوق المشير المالي.`); return `<article class="offer-card"><div class="card-top"><span class="operation ${o.operation==='شراء'?'buy':''}">${safe(o.operation)}</span><span class="status">● ${safe(o.status||'متاح')}</span></div><div><h3>${safe(o.category)}</h3><div class="amount">${safe(o.amount)}</div><div class="price">${safe(o.price||'السعر حسب الاتفاق')}</div></div>${o.description?`<p class="muted">${safe(o.description)}</p>`:''}<div class="meta"><span>⌖ ${safe(o.city)}</span><time>${new Intl.DateTimeFormat('ar-LY',{dateStyle:'medium',timeStyle:'short'}).format(new Date(o.created_at))}</time></div><a class="whatsapp" href="https://wa.me/${phone}?text=${msg}" target="_blank" rel="noopener noreferrer">تواصل عبر WhatsApp</a></article>`}).join('') }
async function loadData(){ try{if(!isConfigured){demoMode=true;offers=demoOffers; $('#statusMessage').textContent='وضع المعاينة: البيانات التالية تجريبية وليست أسعار سوق حقيقية.'; renderOffers();return} const [{data,error},{data:news}]=await Promise.all([supabase.from('offers').select('*').eq('status','published').order('created_at',{ascending:false}),supabase.from('news').select('*').eq('active',true).order('sort_order')]);if(error)throw error;offers=data||[];renderOffers();if(news?.length)$('#tickerContent').innerHTML=news.map(n=>`<span>${safe(n.content)}</span>`).join('')}catch(e){$('#statusMessage').textContent='تعذّر تحميل العروض. تحقق من الاتصال ثم أعد المحاولة.';console.error(e)} }
async function submitOffer(e){e.preventDefault();const form=e.currentTarget, btn=form.querySelector('[type=submit]'),msg=$('#formMessage');if(form.website.value)return;btn.disabled=true;msg.className='form-message';msg.textContent='جارٍ إرسال العرض…';const values=Object.fromEntries(new FormData(form));delete values.website;try{if(!isConfigured)throw new Error('يلزم ربط Supabase أولًا — راجع ملف README.');const {error}=await supabase.rpc('submit_offer',{payload:values});if(error)throw error;form.reset();msg.textContent='تم إرسال عرضك بنجاح، وسيظهر بعد موافقة الإدارة.'}catch(err){msg.className='form-message error';msg.textContent=err.message||'تعذّر الإرسال، حاول لاحقًا.'}finally{btn.disabled=false}}
document.querySelectorAll('.add-trigger').forEach(b=>b.onclick=()=>$('#offerDialog').showModal());$('#offerForm').addEventListener('submit',submitOffer);$('#searchInput').addEventListener('input',renderOffers);renderCategories();loadData()
window.addEventListener('beforeinstallprompt',e=>{e.preventDefault();deferredPrompt=e;$('#installBtn').hidden=false});$('#installBtn').onclick=async()=>{if(deferredPrompt){deferredPrompt.prompt();await deferredPrompt.userChoice;deferredPrompt=null;$('#installBtn').hidden=true}else{const ios=/iphone|ipad|ipod/i.test(navigator.userAgent);$('#installHelp').textContent=ios?'من Safari اضغط زر المشاركة، ثم اختر «إضافة إلى الشاشة الرئيسية».':'افتح قائمة المتصفح واختر «تثبيت التطبيق» أو «إضافة إلى الشاشة الرئيسية».';$('#installDialog').showModal()}};if('serviceWorker'in navigator)window.addEventListener('load',()=>navigator.serviceWorker.register('/sw.js'))
